import {IGraph} from '../../types/graph'

const G: IGraph = {
  "links": [
    {"source": "A", "target": "B", "value": 1},
    {"source": "A", "target": "C", "value": 1},
    {"source": "A", "target": "D", "value": 1},
    {"source": "A", "target": "E", "value": 1},
    {"source": "F", "target": "A", "value": 1},
    {"source": "G", "target": "A", "value": 1},
    {"source": "H", "target": "A", "value": 1},
    {"source": "I", "target": "A", "value": 1},
    {"source": "J", "target": "A", "value": 1},
    {"source": "K", "target": "A", "value": 1},
    {"source": "L", "target": "A", "value": 1},
    {"source": "M", "target": "A", "value": 1},
    {"source": "B", "target": "N", "value": 10},
    {"source": "C", "target": "O", "value": 10},
    {"source": "D", "target": "P", "value": 10},
    {"source": "E", "target": "Q", "value": 10},
    {"source": "F", "target": "R", "value": 10},
    {"source": "G", "target": "S", "value": 10},
    {"source": "H", "target": "T", "value": 10},
    {"source": "I", "target": "U", "value": 10},
    {"source": "J", "target": "V", "value": 10},
    {"source": "K", "target": "W", "value": 10},
    {"source": "L", "target": "X", "value": 10},
    {"source": "M", "target": "Y", "value": 10},
    {"source": "M", "target": "Z", "value": 10},
  ],
  "nodes": [
    {"id": "A", "group": 1},
    {"id": "B", "group": 2},
    {"id": "C", "group": 2},
    {"id": "D", "group": 2},
    {"id": "E", "group": 2},
    {"id": "F", "group": 2},
    {"id": "G", "group": 2},
    {"id": "H", "group": 2},
    {"id": "I", "group": 2},
    {"id": "J", "group": 2},
    {"id": "K", "group": 2},
    {"id": "L", "group": 2},
    {"id": "M", "group": 2},
    {"id": "N", "group": 3},
    {"id": "O", "group": 3},
    {"id": "P", "group": 3},
    {"id": "Q", "group": 3},
    {"id": "R", "group": 3},
    {"id": "S", "group": 3},
    {"id": "T", "group": 3},
    {"id": "U", "group": 3},
    {"id": "V", "group": 3},
    {"id": "W", "group": 3},
    {"id": "X", "group": 3},
    {"id": "Y", "group": 3},
    {"id": "Z", "group": 3},
  ],
}
export default G;